# Generated by Django 4.1 on 2023-02-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_Eleven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('test_subjects', models.CharField(max_length=3)),
                ('test_one', models.CharField(max_length=3)),
                ('test_two', models.CharField(max_length=3)),
                ('mid', models.CharField(max_length=3)),
                ('test_three', models.CharField(max_length=3)),
                ('final', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Grade_Eleven',
            },
        ),
        migrations.CreateModel(
            name='Grade_Nine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('test_subjects', models.CharField(max_length=3)),
                ('test_one', models.CharField(max_length=3)),
                ('test_two', models.CharField(max_length=3)),
                ('mid', models.CharField(max_length=3)),
                ('test_three', models.CharField(max_length=3)),
                ('final', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Grade_Nine',
            },
        ),
        migrations.CreateModel(
            name='Grade_Ten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('test_subjects', models.CharField(max_length=3)),
                ('test_one', models.CharField(max_length=3)),
                ('test_two', models.CharField(max_length=3)),
                ('mid', models.CharField(max_length=3)),
                ('test_three', models.CharField(max_length=3)),
                ('final', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Grade_Ten',
            },
        ),
        migrations.CreateModel(
            name='Grade_Twelve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('test_subjects', models.CharField(max_length=3)),
                ('test_one', models.CharField(max_length=3)),
                ('test_two', models.CharField(max_length=3)),
                ('mid', models.CharField(max_length=3)),
                ('test_three', models.CharField(max_length=3)),
                ('final', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Grade_Twelve',
            },
        ),
        migrations.CreateModel(
            name='New_Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('wanted_class', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=9)),
            ],
        ),
    ]
